overwrite: true
schema: ${GRAPHQL_API:https://api.chriswb.dev/}
documents: ./src/**/*.gql
generates:
  ./src/App/typings/graphql.generated.d.ts:
    plugins:
      - typescript-graphql-files-modules

  ./schema.generated.graphql:
    plugins:
      - schema-ast

  ./src/App/schema/dataModel/personalApi.generated.ts:
    plugins:
      - typescript
    config:
      immutableTypes: true
      namingConvention:
        enumValues: keep

  ./src/App:
    preset: near-operation-file
    presetConfig:
      folder: __generated__
      baseTypesPath: schema/dataModel/personalApi.generated.ts
      extension: .generated.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      dedupeOperationSuffix: true
      pureMagicComment: true
