language: node_js
node_js:
- lts/*
branches:
  only:
  - master
jobs:
  include:
  - name: Check Prettier
    env: TEST_NAME=prettier:check
  - name: Check ESLint
    env: TEST_NAME=lint:js
  - name: Check Stylelint
    env: TEST_NAME=lint:css
  - name: Check typescript
    env: TEST_NAME=typescript
  - name: Builds sucessfully
    env: TEST_NAME=build
script: npm run $TEST_NAME
notifications:
  slack:
    secure: VksoLkBaT31FPf7eQSWt+s4Dimn8qZimziw77T8/l8ZeTNmPOyMczpToZOT1ieqvfycrpwON8Z1PdWmOT2esdPHgPuaYRy+5VkShKfz6ihDcBN0EweKjhj804FrI3j+22D87kQLhyz8ctwPDydLvdWBWuX2YHrcNUlJFU1iTZXSfrQrzuiSL/vXYyxkFI8FMFOaWijuLx6bdWME8637QX+8qv907yWD3H3LvUDbNTWsjZ1Bo3tlHZ9Sy9+EzZb7gHJwp7X3ILdpSJ/kp1gHLWiJdf3s++GX/YA9hoSsI6tZ/ffyY+LKWQGPAoWx1CnM07YnN+w5mB2mHe+vFbmrN+WT8MR4QFLQ0EydewPkQeCegUrTlQWIXbkEE9iWAEkLNL+yEaJLWeX4TXMEnYIAL8Bf2W6iGfRzSwZIxNrfNXGYOR/g7u3PQEXwPx008tRZk4web3Nmx6nCUIgx5aqPGyN71a9ielS3YnA6UN3y66hssSaxRmW5LvD0gMSPf0jQ5+BKjQNX3PSmR/ZFy2y8JVscBtCNuM0FuOcEdGeW3izSumFme+48R7XX1OHz1fxbc6LrCPnTcklLgDYkP5yFiIb8S/AJIEq/UA3OE5ft8f/RfhbHO9qqhsyLLgy8WScn+2vQQ3M7ozOI5Dx/Nob+heDFQd6f/YpyRTYrMxk8X3r4=
