
[build]
  command = "npm run build"
  # functions = "functions" # netlify dev uses this to know where to scaffold and serve your functions
  publish = "dist"

# note: each of these fields are OPTIONAL
[dev]
  command = "npm run devserver" # Command to start your dev server
  targetPort = 8000 # Port of target app server
  publish = "dist" # If you use a _redirect file, provide the path to your static content folder

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true
