
[build]
  functions = "build"

[dev]
  targetPort = 8000
  functionsPort = 9000
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/ssr-server"
  status = 200
  force = true

[[redirects]]
  from = '/*'
  to = '/'
  status = 404

