[build]
  command = "npm run build"
  functions = "functions" #  netlify-lambda reads this
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200
  force = true